/* 
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_code CHAR(6) NOT NULL,
    lead_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
*/
export interface Room {
    id: number;
    join_code: string;
    lead_name: string | null;
    created_at: string;
}

/*
CREATE TABLE estimations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_name TEXT NOT NULL,
    work_item_url TEXT,
    room_id BIGINT REFERENCES rooms(id),
    user_id BIGINT REFERENCES users(id),
    estimate TEXT NOT NULL,
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
*/
export interface Estimation {
    id: number;
    work_item_name: string;
    work_item_url: string | null;
    room_id: number;
    user_id: number;
    estimate: string;
    inserted_at: string;
    updated_at: string;
}

/*
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    room_id CHAR(6) REFERENCES rooms(id),
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
*/
export interface User {
    id: number;
    name: string;
    room_id: number;
    inserted_at: string;
    updated_at: string;
}
